### ISSUE TITLE
About Android TV

### ISSUE THREAD

**Issue by EdgardoMartin** [streamaserver/streama-app#7]
Is there any way to run the application in Android TV?

**Comment by Niach** [comment]
installed it successfully on an philips android tv.
problem is you cant navigate with keyboard/remote controls, but with an usb mouse it works fine

**Comment by palradu** [comment]
I'm interested in this myself. Is there or will there be an Android TV version of the app?

**Comment by WarlaxZ** [comment]
+1 for interest
